[server]
headless = true
enableCORS = false
enableXsrfProtection = false
address = "0.0.0.0"
port = 8501

[browser]
gatherUsageStats = false

[logger]
level = "error"

[theme]
base = "light"
primaryColor = "#005073"
backgroundColor = "#f4f6f9"
secondaryBackgroundColor = "#ffffff"
textColor = "#0f172a"
